// Arc families. Every family is normalised to 12 beats; beat ordinal == semantic role,
// so notes and passages keyed by ordinal survive structure changes without loss.
//
// Beat tuple: [label, purpose, guidance, preferredTags, optionalTags]

export const ROLES = [
  { id: 'opening', name: 'Opening' },
  { id: 'disturbance', name: 'Disturbance' },
  { id: 'hesitation', name: 'Hesitation' },
  { id: 'commitment', name: 'Commitment' },
  { id: 'trials', name: 'Trials' },
  { id: 'deepening', name: 'Deepening' },
  { id: 'midpoint', name: 'Midpoint' },
  { id: 'pressure', name: 'Pressure' },
  { id: 'crisis', name: 'Crisis' },
  { id: 'reckoning', name: 'Reckoning' },
  { id: 'climax', name: 'Climax' },
  { id: 'resolution', name: 'Resolution' },
]

const F = (id, name, blurb, beats) => ({
  id, name, blurb,
  beats: beats.map(([label, purpose, guidance, preferredTags, optionalTags = []], ordinal) => ({
    id: `${id}.${ordinal}`, ordinal, role: ROLES[ordinal].id, label, purpose, guidance, preferredTags, optionalTags,
  })),
})

export const FAMILIES = [
  F('hero', "Hero's Journey", 'A departure into the unknown, an ordeal, and a return bearing a gift.', [
    ['The Ordinary World', 'Establish home, the hero’s lack, and what is at stake.', 'Show a normal day that is quietly not enough.', ['protagonist', 'world'], ['flaw', 'desire']],
    ['The Call', 'Something summons the hero away.', 'Make the call specific: a person, a message, a disaster.', ['inciting-incident'], ['mystery', 'desire']],
    ['Refusal', 'The hero resists, revealing fear.', 'Let the refusal be reasonable — and costly.', ['flaw', 'need'], ['relationship']],
    ['Crossing the Threshold', 'The hero commits and leaves the known world.', 'Mark the crossing with a physical border.', ['threshold'], ['mentor', 'world']],
    ['Road of Trials', 'Tests that teach the new world’s rules.', 'Fail at least once. Reveal a rule of the world.', ['world-rule', 'set-piece'], ['ally', 'scarcity']],
    ['Allies and Enemies', 'The hero learns who can be trusted.', 'Introduce a companion with their own agenda.', ['ally', 'rival'], ['relationship']],
    ['Approach the Inmost Cave', 'Preparation for the central ordeal.', 'Raise the stakes; show what the hero stands to lose.', ['stakes', 'antagonist'], ['place']],
    ['The Ordeal', 'A confrontation with death or deepest fear.', 'Something must truly die — hope, a person, a belief.', ['lowest-point', 'antagonist'], ['sacrifice']],
    ['The Reward', 'The hero seizes the prize — at a price.', 'The reward should be double-edged.', ['desire', 'reversal'], ['secret']],
    ['The Road Back', 'Consequences chase the hero home.', 'Pursuit, time pressure, or a new betrayal.', ['antagonist', 'stakes'], ['relationship']],
    ['Resurrection', 'Final test using everything learned.', 'The hero wins by being who they have become.', ['climax', 'need'], ['sacrifice']],
    ['Return with the Elixir', 'Home transformed by what the hero brings.', 'Mirror the opening scene with a difference.', ['ending-image'], ['theme-question', 'motif']],
  ]),
  F('three-act', 'Three-Act Quest', 'Clear goal, escalating obstacles, decisive finale.', [
    ['Setup', 'Introduce the protagonist, goal, and world.', 'Open on action that characterises.', ['protagonist', 'world'], ['desire']],
    ['Inciting Incident', 'The event that sets the quest in motion.', 'Make it impossible to ignore.', ['inciting-incident'], ['antagonist']],
    ['Debate', 'Weighing the risks of the quest.', 'Let a trusted voice argue against going.', ['flaw', 'relationship'], ['ally']],
    ['Plot Point One', 'A choice locks the protagonist in.', 'End Act One with a door slamming shut.', ['threshold'], ['stakes']],
    ['Rising Obstacles', 'Complications accumulate.', 'Each obstacle is harder and more personal.', ['conflict', 'scarcity'], ['world-rule']],
    ['Fun and Games', 'The promise of the premise delivered.', 'Show the scenes readers came for.', ['set-piece'], ['ally', 'place']],
    ['Midpoint', 'A false victory or false defeat.', 'Shift from reacting to acting.', ['reversal'], ['twist']],
    ['Bad Guys Close In', 'Opposition regroups and strikes.', 'Internal doubts grow alongside external threats.', ['antagonist', 'stakes'], ['rival']],
    ['All Is Lost', 'The lowest point.', 'Take away the protagonist’s last support.', ['lowest-point'], ['sacrifice']],
    ['Dark Night', 'Reflection and new resolve.', 'A small memory or clue sparks the solution.', ['need', 'clue'], ['theme-question']],
    ['Finale', 'The decisive confrontation.', 'Use every planted setup.', ['climax'], ['antagonist']],
    ['Final Image', 'The new normal.', 'Contrast with the opening.', ['ending-image'], ['ending']],
  ]),
  F('tragedy', 'Five-Act Tragedy', 'A great person undone by the very quality that raised them.', [
    ['Exposition', 'Establish greatness and its shadow.', 'Show the flaw as a virtue first.', ['protagonist', 'flaw'], ['world']],
    ['The Exciting Force', 'Ambition or opportunity awakens.', 'Offer a temptation that fits the flaw exactly.', ['desire', 'inciting-incident'], ['secret']],
    ['Warnings Ignored', 'Someone foresees the fall.', 'Give the warning to a character nobody listens to.', ['ally', 'relationship'], ['mentor']],
    ['The Fateful Act', 'A choice that cannot be undone.', 'Let it look like triumph.', ['threshold', 'sacrifice'], ['stakes']],
    ['Rising Fortune', 'The protagonist gains power.', 'Show the cost falling on others.', ['world-rule', 'scarcity'], ['conflict']],
    ['Complicity', 'Allies are drawn into guilt.', 'A loyal friend makes a compromise.', ['relationship', 'secret'], ['ally']],
    ['The Climax of Power', 'Peak of success; the turn begins.', 'At the height, a crack appears.', ['reversal'], ['clue']],
    ['Unravelling', 'Consequences multiply.', 'Enemies unite; secrets surface.', ['antagonist', 'rival'], ['secret']],
    ['Isolation', 'The protagonist is alone with the truth.', 'Strip away every relationship.', ['lowest-point'], ['relationship']],
    ['Recognition', 'The protagonist finally sees.', 'Recognition should come too late, but it must come.', ['need', 'theme-question'], ['twist']],
    ['Catastrophe', 'The fall.', 'Make the ending feel inevitable and still shocking.', ['climax', 'stakes'], ['sacrifice']],
    ['Aftermath', 'What survives the fall.', 'Let a minor character carry the lesson forward.', ['ending-image'], ['theme']],
  ]),
  F('mystery', 'Mystery Spiral', 'A question that deepens with every answer.', [
    ['The Crime or Question', 'Something is wrong and unexplained.', 'Open on the absence, not the event.', ['mystery', 'inciting-incident'], ['world']],
    ['The Investigator', 'Who seeks the truth, and why them?', 'Give them a personal reason to care.', ['protagonist', 'desire'], ['flaw']],
    ['First Clues', 'Initial evidence and suspects.', 'Plant one true clue among red herrings.', ['clue'], ['place']],
    ['Suspects', 'Everyone has something to hide.', 'Each suspect lies about something unrelated.', ['secret', 'relationship'], ['rival']],
    ['Deeper In', 'Investigation reveals a larger pattern.', 'The case connects to the investigator’s past.', ['world-rule', 'secret'], ['mystery']],
    ['The Warning', 'Someone wants the search stopped.', 'Make the threat intimate.', ['antagonist', 'stakes'], ['conflict']],
    ['False Solution', 'An answer that seems right.', 'Let the reader believe it too.', ['reversal'], ['clue']],
    ['Second Crime', 'The stakes escalate.', 'The new event invalidates the false solution.', ['stakes', 'twist'], ['inciting-incident']],
    ['Cold Trail', 'Leads collapse.', 'The investigator doubts their own judgement.', ['lowest-point', 'flaw'], ['relationship']],
    ['The Overlooked Detail', 'A planted clue clicks into place.', 'Return to an early scene with new eyes.', ['clue', 'need'], ['motif']],
    ['The Reveal', 'The truth is confronted.', 'The culprit’s logic should be coherent.', ['climax', 'antagonist'], ['secret']],
    ['What the Truth Costs', 'The world after knowing.', 'Answer the question; open a smaller one.', ['ending-image'], ['theme-question']],
  ]),
  F('heist', 'Heist Clock', 'A crew, a plan, a ticking clock, and everything going wrong.', [
    ['The Score', 'Something valuable is out of reach.', 'Describe the prize and the impossible vault.', ['desire', 'world'], ['scarcity']],
    ['The Reason', 'Why now, why this crew leader?', 'A personal debt or wrong to right.', ['inciting-incident', 'protagonist'], ['stakes']],
    ['Assembling the Crew', 'Gather specialists.', 'Each recruit has a flaw that will matter.', ['ally', 'relationship'], ['rival']],
    ['The Plan', 'Walk through how it should go.', 'Let the reader see the plan — or deliberately not.', ['threshold', 'world-rule'], ['place']],
    ['Rehearsal', 'Practice reveals cracks.', 'One test fails in a small, telling way.', ['set-piece', 'flaw'], ['clue']],
    ['The Mark', 'Meet the target up close.', 'The target should be clever and human.', ['antagonist'], ['secret']],
    ['Go Time', 'The heist begins; the clock starts.', 'Give a precise deadline.', ['set-piece', 'stakes'], ['conflict']],
    ['Complication', 'An unforeseen variable appears.', 'Improvise under pressure.', ['reversal', 'scarcity'], ['antagonist']],
    ['Betrayal', 'Someone inside turns.', 'Seed the betrayal earlier.', ['twist', 'secret'], ['relationship']],
    ['The Real Plan', 'The hidden layer is revealed.', 'Reframe earlier scenes.', ['clue', 'twist'], ['reversal']],
    ['The Getaway', 'Escape with the prize — or without.', 'Physical, fast, and costly.', ['climax'], ['sacrifice']],
    ['The Split', 'Who gets what, and what it meant.', 'The real prize was never the score.', ['ending-image', 'theme'], ['relationship']],
  ]),
  F('romance', 'Romance / Bond Arc', 'Two people resist, then risk everything, to be together.', [
    ['Separate Lives', 'Each lead’s wound and walls.', 'Show why they aren’t ready for each other.', ['protagonist', 'need'], ['flaw']],
    ['The Meeting', 'An unforgettable first encounter.', 'Friction and spark at once.', ['inciting-incident', 'relationship'], ['place']],
    ['Resistance', 'Reasons they can’t be together.', 'External obstacle plus internal fear.', ['flaw', 'world-rule'], ['conflict']],
    ['Forced Together', 'Circumstance binds them.', 'A shared task or confined space.', ['threshold', 'relationship'], ['scarcity']],
    ['Getting Closer', 'Walls come down.', 'A moment of real seeing.', ['relationship', 'secret'], ['motif']],
    ['The Rival', 'A third force complicates things.', 'Make the alternative genuinely appealing.', ['rival'], ['ally']],
    ['Almost', 'An intimate moment or first confession.', 'Interrupt it — or let it land and terrify them.', ['reversal', 'relationship'], ['set-piece']],
    ['Doubt', 'Old wounds reassert themselves.', 'A misunderstanding rooted in a real fear.', ['flaw', 'secret'], ['stakes']],
    ['Breakup', 'The bond breaks.', 'Both are partly right.', ['lowest-point'], ['sacrifice']],
    ['Realisation', 'What each has learned.', 'They grow separately first.', ['need', 'theme-question'], ['ally']],
    ['Grand Gesture', 'Risking everything for the bond.', 'The gesture uses what we learned about them.', ['climax', 'sacrifice'], ['set-piece']],
    ['Together, Changed', 'A new shared life.', 'Show the ritual they now share.', ['ending-image', 'relationship'], ['motif']],
  ]),
  F('redemption', 'Redemption Arc', 'A person who did harm seeks to repair it.', [
    ['The Sin', 'What the protagonist did.', 'Don’t soften it.', ['protagonist', 'secret'], ['flaw']],
    ['Living With It', 'The shape of their guilt.', 'Show avoidance, numbing, or cruelty.', ['flaw', 'world'], ['need']],
    ['The Opportunity', 'A chance to make amends appears.', 'It should require facing the victim or their world.', ['inciting-incident'], ['relationship']],
    ['Reluctant Step', 'The first attempt at change.', 'Clumsy, self-serving, incomplete.', ['threshold', 'desire'], ['ally']],
    ['Mistrust', 'Others doubt the change.', 'Rightly so.', ['relationship', 'rival'], ['world-rule']],
    ['Small Proof', 'An act of genuine goodness.', 'Unseen by anyone who matters.', ['set-piece', 'need'], ['motif']],
    ['The Past Returns', 'Old associates or consequences resurface.', 'Temptation to revert.', ['antagonist', 'reversal'], ['secret']],
    ['Backslide', 'The protagonist falls back.', 'The old skills are useful — that’s the danger.', ['flaw', 'stakes'], ['conflict']],
    ['Exposure', 'The truth comes out fully.', 'Lose what was newly gained.', ['lowest-point', 'secret'], ['relationship']],
    ['Acceptance', 'Owning the harm without excuse.', 'Apology without expectation.', ['theme-question', 'need'], ['mentor']],
    ['The Price', 'An act of restoration that costs dearly.', 'Pay in the currency that matters most to them.', ['climax', 'sacrifice'], ['stakes']],
    ['Grace', 'What forgiveness looks like, if it comes.', 'It may be partial. That is enough.', ['ending-image'], ['theme']],
  ]),
  F('coming-of-age', 'Coming-of-Age', 'A young person learns who they are by losing who they were.', [
    ['Innocence', 'The protagonist’s certainties.', 'Show a belief the world will break.', ['protagonist', 'world'], ['desire']],
    ['First Crack', 'A glimpse of the adult world.', 'Something overheard, seen, or found.', ['inciting-incident', 'secret'], ['mystery']],
    ['Clinging', 'Holding onto childhood.', 'A ritual, place, or friend that anchors them.', ['relationship', 'motif'], ['place']],
    ['Leaving the Nest', 'A step into independence.', 'Literal or emotional departure.', ['threshold'], ['desire']],
    ['New Tribe', 'Finding people outside family.', 'Belonging comes with rules.', ['ally', 'world-rule'], ['rival']],
    ['Mentor or False Idol', 'An adult to emulate.', 'They are flawed in ways the protagonist can’t see yet.', ['mentor', 'antagonist'], ['secret']],
    ['Transgression', 'Breaking a rule to belong.', 'Thrilling, then frightening.', ['reversal', 'flaw'], ['set-piece']],
    ['Consequences', 'The fallout lands.', 'Someone else pays too.', ['stakes', 'relationship'], ['conflict']],
    ['Disillusion', 'The idol falls; the tribe fractures.', 'Grief for what they believed.', ['lowest-point'], ['twist']],
    ['Choosing Self', 'Deciding what they value.', 'A quiet internal choice.', ['need', 'theme-question'], ['voice']],
    ['The Test', 'Acting on new values publicly.', 'It should cost social standing.', ['climax', 'sacrifice'], ['stakes']],
    ['Looking Back', 'Seeing the child they were.', 'Return to the anchor from beat three.', ['ending-image', 'motif'], ['place']],
  ]),
  F('horror', 'Horror Descent', 'Safety erodes until something unspeakable is faced.', [
    ['False Safety', 'A place that feels safe.', 'Linger on comfort so its loss hurts.', ['world', 'place'], ['protagonist']],
    ['The Wrongness', 'A small uncanny detail.', 'Understate it.', ['inciting-incident', 'mystery'], ['clue']],
    ['Rationalisation', 'Explaining it away.', 'The explanation almost works.', ['flaw', 'world-rule'], ['relationship']],
    ['No Way Out', 'Escape becomes impossible.', 'Cut off help, light, or exits.', ['threshold', 'scarcity'], ['place']],
    ['Escalation', 'The threat grows bolder.', 'Show its rules by breaking a character.', ['antagonist', 'world-rule'], ['set-piece']],
    ['Research', 'Learning what it is.', 'The history is worse than the present.', ['secret', 'clue'], ['mystery']],
    ['The First Loss', 'Someone is taken.', 'Make us love them first.', ['stakes', 'relationship'], ['sacrifice']],
    ['Paranoia', 'The group turns inward.', 'The human threat rivals the monster.', ['rival', 'conflict'], ['secret']],
    ['The Pit', 'Alone with the thing.', 'Sensory detail; minimal explanation.', ['lowest-point', 'sensory'], ['antagonist']],
    ['Understanding', 'Grasping how it works — or what it wants.', 'The answer implicates the protagonist.', ['twist', 'need'], ['theme-question']],
    ['Confrontation', 'Facing it with what remains.', 'Victory, if any, is partial.', ['climax'], ['sacrifice']],
    ['The Stain', 'What lingers after.', 'One last uncanny detail.', ['ending-image', 'motif'], ['mystery']],
  ]),
  F('voyage', 'Voyage and Return', 'A journey into a strange land and back, changed.', [
    ['Before', 'The protagonist’s narrow life.', 'A small dissatisfaction.', ['protagonist', 'world'], ['desire']],
    ['Falling In', 'Accidental passage to the strange world.', 'A door, storm, sleep, or wrong turn.', ['inciting-incident', 'threshold'], ['mystery']],
    ['Wonder', 'Delight in the strange.', 'Show a marvel in precise detail.', ['world', 'set-piece'], ['sensory']],
    ['Rules of the Place', 'Learning how things work here.', 'A rule that contradicts home.', ['world-rule'], ['scarcity']],
    ['A Guide', 'Someone native helps.', 'Their help has a hidden price.', ['ally', 'mentor'], ['secret']],
    ['Unease', 'The wonder sours.', 'A beautiful thing turns out to be cruel.', ['reversal', 'world'], ['motif']],
    ['The Shadow', 'The strange world’s threat emerges.', 'Personify it.', ['antagonist'], ['stakes']],
    ['Trapped', 'The way home is lost.', 'The rules now prevent leaving.', ['stakes', 'world-rule'], ['conflict']],
    ['Nightmare', 'The threat closes in.', 'The guide is compromised.', ['lowest-point', 'relationship'], ['twist']],
    ['The Key', 'Finding the way back.', 'It requires something learned here.', ['clue', 'need'], ['sacrifice']],
    ['Escape', 'The flight home.', 'Chased to the very threshold.', ['climax'], ['set-piece']],
    ['Home Again', 'The ordinary, newly seen.', 'Bring back one impossible object.', ['ending-image', 'motif'], ['theme']],
  ]),
  F('rebellion', 'Rebellion / Underdog', 'The weak organise against the powerful.', [
    ['Under the Boot', 'Everyday oppression.', 'Show how people adapt to injustice.', ['world', 'scarcity'], ['world-rule']],
    ['The Spark', 'An outrage too far.', 'Personal and public at once.', ['inciting-incident', 'stakes'], ['antagonist']],
    ['Unlikely Leader', 'Someone steps up reluctantly.', 'They have a reason to stay quiet.', ['protagonist', 'flaw'], ['need']],
    ['Organising', 'Gathering allies.', 'Each ally has a different reason to fight.', ['ally', 'relationship'], ['rival']],
    ['First Strike', 'A small victory.', 'Make it clever, not strong.', ['set-piece', 'threshold'], ['clue']],
    ['Crackdown', 'The powerful respond.', 'Collective punishment.', ['antagonist', 'stakes'], ['world-rule']],
    ['Division', 'The movement fractures.', 'Moderates vs. radicals.', ['rival', 'conflict'], ['theme-question']],
    ['The Informer', 'A traitor within.', 'Their reasons are sympathetic.', ['secret', 'twist'], ['relationship']],
    ['Crushed', 'The movement is broken.', 'The leader is captured or disgraced.', ['lowest-point'], ['sacrifice']],
    ['The Symbol', 'An image or act reignites hope.', 'It comes from someone overlooked.', ['motif', 'reversal'], ['ally']],
    ['Uprising', 'Everyone rises.', 'Small people doing small brave things at scale.', ['climax', 'set-piece'], ['sacrifice']],
    ['The New Order', 'What replaces the old.', 'Show the risk of becoming what they fought.', ['ending-image', 'theme'], ['world']],
  ]),
  F('fable', 'Fable / Moral Transformation', 'A simple tale that tests a virtue and reveals a truth.', [
    ['Once There Was', 'A character defined by one trait.', 'Simple, vivid, almost archetypal.', ['protagonist', 'flaw'], ['world']],
    ['The Setting', 'A place with a moral rule.', 'The rule should be stated plainly.', ['world-rule', 'world'], ['motif']],
    ['The Temptation', 'A chance to break the rule.', 'Offer exactly what they crave.', ['desire', 'inciting-incident'], ['antagonist']],
    ['The Choice', 'They choose according to their flaw.', 'Let it feel natural.', ['threshold', 'flaw'], ['need']],
    ['Early Reward', 'The choice seems to pay off.', 'Enjoy the fruits.', ['set-piece', 'desire'], ['scarcity']],
    ['A Stranger', 'Someone arrives with a test.', 'A disguised figure is traditional.', ['mentor', 'mystery'], ['secret']],
    ['Repetition', 'The pattern repeats, larger.', 'Rule of three.', ['reversal', 'motif'], ['conflict']],
    ['The Turn', 'Consequences arrive.', 'Poetic justice.', ['stakes', 'antagonist'], ['relationship']],
    ['Loss', 'What the flaw costs.', 'Lose the thing they valued most.', ['lowest-point', 'sacrifice'], ['relationship']],
    ['Wisdom', 'The lesson learned.', 'Earned, not stated.', ['need', 'theme-question'], ['mentor']],
    ['The Final Test', 'Offered the temptation again.', 'Choose differently.', ['climax'], ['sacrifice']],
    ['The Moral', 'The world rebalanced.', 'End on an image, not a lecture.', ['ending-image', 'theme'], ['motif']],
  ]),
  F('puzzle-box', 'Puzzle Box / Reality Bend', 'Reality is not what it seems, and the rules keep shifting.', [
    ['The Surface', 'Reality looks normal.', 'Include one detail that doesn’t add up.', ['world', 'clue'], ['protagonist']],
    ['The Glitch', 'Reality visibly breaks.', 'Repetition, impossibility, or contradiction.', ['inciting-incident', 'mystery'], ['world-rule']],
    ['Denial', 'Trying to live normally.', 'The glitches follow.', ['flaw', 'relationship'], ['motif']],
    ['Down the Rabbit Hole', 'Choosing to investigate.', 'A door that should not exist.', ['threshold'], ['place']],
    ['New Rules', 'Mapping the altered reality.', 'Experiment and record.', ['world-rule', 'clue'], ['set-piece']],
    ['Another Who Knows', 'Meeting someone else aware.', 'Can they be trusted?', ['ally', 'secret'], ['rival']],
    ['The Rules Change', 'Everything learned is wrong.', 'A deeper layer.', ['reversal', 'twist'], ['world-rule']],
    ['The Architect', 'Glimpsing who or what is behind it.', 'Motive before identity.', ['antagonist', 'mystery'], ['secret']],
    ['Lost in Loops', 'Identity itself becomes uncertain.', 'Question the protagonist’s memories.', ['lowest-point', 'need'], ['motif']],
    ['The Pattern', 'Seeing the whole design.', 'Every glitch was a message.', ['clue', 'theme-question'], ['twist']],
    ['Breaking Through', 'Acting outside the rules.', 'Do the one thing the system can’t predict.', ['climax'], ['sacrifice']],
    ['Which Reality?', 'An ambiguous new normal.', 'Leave one thread deliberately loose.', ['ending-image'], ['mystery']],
  ]),
  F('ensemble', 'Ensemble Mosaic', 'Many lives converge on one event.', [
    ['Scattered Lives', 'Introduce several perspectives.', 'Each with a distinct want.', ['protagonist', 'world'], ['relationship']],
    ['The Common Thread', 'An event connects them.', 'They don’t yet know they’re connected.', ['inciting-incident', 'mystery'], ['motif']],
    ['Separate Troubles', 'Each thread’s own problem.', 'Parallel structure; contrasting tones.', ['conflict', 'desire'], ['flaw']],
    ['First Crossing', 'Two threads collide.', 'An accident, a meeting, a misunderstanding.', ['threshold', 'relationship'], ['place']],
    ['Webs', 'Relationships form and knot.', 'An unlikely friendship.', ['relationship', 'ally'], ['rival']],
    ['Secrets Shared', 'Private truths pass between threads.', 'Information changes hands.', ['secret'], ['clue']],
    ['Convergence', 'All threads approach one place.', 'A gathering, disaster, or deadline.', ['set-piece', 'stakes'], ['place']],
    ['Fracture', 'Conflicts between threads.', 'Needs directly oppose each other.', ['conflict', 'rival'], ['reversal']],
    ['Collective Low', 'Everyone’s worst moment at once.', 'Intercut rapidly.', ['lowest-point'], ['stakes']],
    ['Unexpected Help', 'Threads rescue each other.', 'The minor character matters most.', ['ally', 'reversal'], ['twist']],
    ['The Event', 'The shared climax.', 'Each thread resolves inside it.', ['climax'], ['sacrifice']],
    ['Mosaic', 'The full picture.', 'Pull back to show the pattern.', ['ending-image', 'theme'], ['motif']],
  ]),
  F('meaning', 'Quest for Meaning', 'A search for purpose that finds something unexpected.', [
    ['Emptiness', 'Life without meaning.', 'Routine and quiet despair.', ['protagonist', 'need'], ['world']],
    ['A Question', 'Something makes them ask why.', 'A death, birth, letter, or loss.', ['inciting-incident', 'theme-question'], ['mystery']],
    ['Old Answers', 'Trying familiar sources.', 'Religion, work, family — each fails in its way.', ['relationship', 'world'], ['flaw']],
    ['Setting Out', 'Leaving to search.', 'A pilgrimage, move, or new vocation.', ['threshold', 'desire'], ['place']],
    ['Teachers', 'Meeting those with answers.', 'Each has part of the truth.', ['mentor', 'ally'], ['world-rule']],
    ['A Glimpse', 'A moment of transcendence.', 'Brief, sensory, impossible to hold.', ['set-piece', 'sensory'], ['motif']],
    ['Doubt', 'The glimpse fades.', 'Was it real?', ['reversal', 'flaw'], ['secret']],
    ['Temptation of Certainty', 'An easy false answer.', 'A cult, cause, or comfortable lie.', ['antagonist'], ['rival']],
    ['The Void', 'Losing faith in the search.', 'Nothing means anything.', ['lowest-point'], ['stakes']],
    ['Ordinary Grace', 'Meaning found in the small.', 'A stranger’s kindness, a task done well.', ['need', 'relationship'], ['theme']],
    ['The Choice to Live', 'Choosing a purpose.', 'Commitment without certainty.', ['climax', 'sacrifice'], ['theme-question']],
    ['Returning', 'Home, seen differently.', 'The same routine, now luminous.', ['ending-image', 'motif'], ['world']],
  ]),
]
